name: pbnhs
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  cloud_firestore: ^5.6.3
  json_annotation: ^4.9.0
  firebase_auth: ^5.4.2
  auto_route: ^9.3.0+1
  flutter_bloc: ^9.0.0
  firebase_core: ^3.11.0
  file_picker: ^9.0.0
  firebase_storage: ^12.4.3
  intl: ^0.20.2
  universal_html: ^2.2.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  auto_route_generator: ^9.3.1
  flutter_gen_runner: ^5.9.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
